<?php
//In form alter 
// add custom validation function


function givefeedback_form_give_feedback_node_form_alter(&$form, &$form_state, $form_id){
	
	dpm($form_state);
	dpm($form);
	$form['#validate'][] = 'new_valid_function';
}
	  		 
  	 
  //In custom validation function
  // check whether the selected time period is valid
    // check if current has not given more than one feedback for the selected target user for the selected time period.

		
function new_valid_function(&$form, &$form_state) {
//dpm($form_state);
	
	global $user;

	$query1 = db_select('node', 'n')
	       ->condition('n.uid', $user->uid, '=')
	       ->condition('n.type','give_feedback','=')
	       ->fields('n', array('nid', 'type','created'));
	$result1 = $query1->execute();
	$options = $result1->fetchAll();


	foreach ($options as $key => $value) {
		$nid = $value->nid;
		$timestamp = $value->created;
		$feed = node_load($nid);
		// dpm($feed);
		$user_id = field_get_items('node', $feed, 'field_users')[0]['target_id'];
		$user_period = field_get_items('node', $feed, 'field_time_line')[0]['tid'];

		$user_date = format_date($timestamp ,'custom','d');
		$user_month = format_date($timestamp ,'custom','m');

		$current_user_timestamp = $user->timestamp;
		$current_user_date = format_date($current_user_timestamp,'custom','d');
		$current_user_month = format_date($current_user_timestamp,'custom','m');
		dpm($current_user_month);


		if($current_user_date > '5' and $current_user_date < '15') {
		 	if($form_state['input']['field_time_line']['und'] != '25') {
		 		form_set_error('field_time_line', t('Please select PERIOD-I.'));
		 	}

			else {

			 if($form_state['input']['field_time_line']['und'] == $user_period) {


		  	 	if ($form_state['input']['field_users']['und'] == $user_id and $form_state['input']['field_time_line']['und'] == $user_period and $current_user_month == $user_month) {

		  	 		form_set_error('field_users', t('Feedback has already been given for this particular user in this period.'));
		  	 	}

		  	 	else {
		  	 		continue;
		  	 	}
			  }
	  	} 	
		}




		if($current_user_date > '20' and $current_user_date <= '31') {
			if($form_state['input']['field_time_line']['und'] != '26') {
				form_set_error('field_time_line', t('Please select PERIOD-II.'));
			}

			else {

				if($form_state['input']['field_time_line']['und'] == $user_period){

					if ($form_state['input']['field_users']['und'] == $user_id and $form_state['input']['field_time_line']['und'] == $user_period and $current_user_month == $user_month) {

			  	 		form_set_error('field_users', t('Feedback has already been given for this particular user in this period.'));
		  	 	}


		  	 	else {
		  	 		continue;
		  	 	}
				}
			}
		}


		if(($current_user_date >= '1' and $current_user_date <= '5') || ($current_user_date >= '15' and $current_user_date <= '20')) {

			if($form_state['input']['field_time_line']['und'] == $user_period) {

				if ($form_state['input']['field_users']['und'] == $user_id and $form_state['input']['field_time_line']['und'] == $user_period and $current_user_month == $user_month) {

	  	 		form_set_error('field_users', t('Feedback has already been given for this particular user in this period.'));
	  	 	}

	  	 	else if($form_state['input']['field_users']['und'] == $user_id and $form_state['input']['field_time_line']['und'] == $user_period and ($current_user_month-1) == $user_month) {

	  	 			form_set_error('field_users', t('Feedback has already been given for this particular user in this period.'));
	  	 	}


				else{
	  	 		continue;
	  	 	}
			}
		}
	}  
} 



	





 
  	
	


